language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev libcups2-dev sloccount
install: "pip install -r requirements.txt"
script: ./make tests
